services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./apps/web:/app
      - /app/node_modules

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '8787:8787'
    volumes:
      - ./apps/api:/app
      - /app/node_modules
